name: file_serve_app
description: A simple file server app for Android

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  intl: ^0.18.1
  network_info_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/web/
